### ISSUE TITLE
Close button on help panel obscures text slightly

### ISSUE THREAD

**Issue by ToonTalk** [afsheenam/UUI#4]
E.g. hard to see the word "It" because of the 'x' close button:

![image](https://user-images.githubusercontent.com/2138696/29511092-4a8eeb7c-865e-11e7-9181-a5f3927ad778.png)

**Comment by afsheenam** [comment]
I have 2 ways to fix that:
- Add more padding
- Have a heading on top of the page that shows the name of the tool that the help box represents.

I prefer the 2nd option. What do you think?

**Comment by ToonTalk** [comment]
I agree the heading sounds like a good idea.

**Comment by afsheenam** [comment]
Solved by adding heading to the help text
